from fastapi import FastAPI, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.orm import Session
from sqlalchemy import text, func
from src.core.database import get_db, engine
from src.core.models import Base, Driver, Trip

# This automatically creates any missing tables (like 'trips') when the server boots
Base.metadata.create_all(bind=engine)

app = FastAPI(title="Uber for Dogs API", version="0.1.0")

class RideRequest(BaseModel):
    dog_name: str
    breed: str
    pickup_lon: float
    pickup_lat: float

@app.get("/health")
def health_check(db: Session = Depends(get_db)):
    try:
        db.execute(text("SELECT 1"))
        db_status = "connected"
    except Exception as e:
        db_status = f"disconnected ({e})"
    return {"status": "sniffing_around", "service": "online", "database": db_status}

@app.post("/api/v1/rides/request")
def request_ride(payload: RideRequest, db: Session = Depends(get_db)):
    pickup_point = func.ST_SetSRID(func.ST_MakePoint(payload.pickup_lon, payload.pickup_lat), 4326)

    result = db.query(
        Driver,
        func.ST_DistanceSphere(Driver.current_location, pickup_point).label("distance_meters")
    ).filter(Driver.is_online == True) \
     .order_by(func.ST_DistanceSphere(Driver.current_location, pickup_point)) \
     .first()

    if not result:
        raise HTTPException(status_code=404, detail="No available drivers nearby.")

    driver, distance_meters = result

    # Create the pending trip in the database
    new_trip = Trip(
        dog_name=payload.dog_name,
        pickup_lon=payload.pickup_lon,
        pickup_lat=payload.pickup_lat,
        driver_id=driver.id,
        status="requested"
    )
    db.add(new_trip)
    db.commit()
    db.refresh(new_trip) # Retrieves the new trip ID generated by PostgreSQL

    distance_miles = round(distance_meters * 0.000621371, 2)
    eta_minutes = max(1, int(distance_miles * 3))

    return {
        "message": "Ping sent to nearest driver!",
        "trip_id": new_trip.id,
        "driver_id": driver.id,
        "dispatch_details": {
            "driver_name": driver.dog_name,
            "distance_miles": distance_miles,
            "eta_minutes": eta_minutes
        }
    }

@app.post("/api/v1/trips/{trip_id}/accept")
def accept_trip(trip_id: int, driver_id: int, db: Session = Depends(get_db)):
    # Verify the trip exists and was actually offered to this specific driver
    trip = db.query(Trip).filter(Trip.id == trip_id, Trip.driver_id == driver_id).first()
    
    if not trip:
        raise HTTPException(status_code=404, detail="Trip not found or driver mismatch.")
    
    if trip.status != "requested":
        raise HTTPException(status_code=400, detail=f"Cannot accept trip. Current status is: {trip.status}")

    # Update the state machine
    trip.status = "accepted"
    db.commit()
    
    return {
        "message": "Trip accepted! The driver is on their way.",
        "trip_id": trip.id,
        "status": trip.status
    }